Skydio/revup

- revup/topic_stack.py
Lower the topic name and make it only
take words from the title line.
> Clean up --auto-topic topics

- README.md
This ought to fix rendering issues on pypi.
Reviewers: aaron-skydio
> Add absolute paths to images in README

- .github/workflows/makefile.yml
- .gitignore
- Makefile
Run checks under multiple python versions
and also check the package build and lint.
Reviewers: greg-b
> Add more github action tests

- .github/workflows/makefile.yml
- Makefile
- tests/test_tools.py
Signed-off-by: Greg Balke <gbalke@berkeley.edu>
Topic: cli_unit_test_framework
Reviewers: jerry-skydio
Relative: github_workflow_python_install
> [Test] Initial unit test framework

- revup/amend.py
The output will look like this
```
user@host:~/revup$ revup amend --insert
\# Please enter the commit message for your changes. Lines starting
\# with '#' will be ignored, and an empty message aborts the commit.
\#
\# Topics found between HEAD and origin/master
\#  my_topic
\#  my_other_topic
\#
```
Topic: revup_topic_in_commit_message
> Add revup topics bewteen HEAD and relative branch to revup commit string comment

- revup/revup.py
- revup/toolkit.py
Use for finding divergence point between branches.
topic: fork-pt
> Add fork-point command to toolkit

- .github/workflows/makefile.yml
> Run CI on all branches

- revup/amend.py
- revup/git.py
- revup/topic_stack.py
> Shortcut base branch detection if only one possible branch

- revup/amend.py
This makes it consistent with the order you'd see
in "git log".
Topic: amend_reverse
Reviewers: brian-k, malcolm
> Reverse order of topics in amend

- revup/git.py
- revup/revup.py
- revup/toolkit.py
This can be used to find where branches
diverge.
Topic: closest-b
> toolkit: Add closest-branch command

- revup/revup.py
> shell: Don't check permissions on window

- revup/amend.py
- revup/git.py
- revup/topic_stack.py
Newer versions of black / mypy have slightly new
requirements.
Optional can't be implied, so make it explicit.
Run format again as some formatting has changed.
Topic: fix
> lint: Fix lint failures

- revup/github_utils.py
Topic: lint
Reviewers: brian-k, aaron
> lint: Run format to account for black upgrade

- revup/toolkit.py
> toolkit: Fix await statements

- revup/topic_stack.py
Make upload run faster if we know there is nothing to upload by
skipping the query step.
Topic: skip
> Skip querying on an empty upload

- revup/cherry_pick.py
Will only attempt to fetch if the branch isn't found locally, and will
still fail if it isn't found after fetching
Topic: cherry-pick-fetch
> Revup cherry-pick attempts to fetch

- revup/amend.py
Git commit has several configuration options
for how to strip comment lines out of the commit
text. We generally want to support these because
they affect whether we throw away prefixed lines
that could be important text to the user.
"strip" is just the default way we've been doing it, so
refactor to also support "scissors" which has a different
comment and removal method. "whitespace" and "verbatim"
are simpler strategies that we can support as well, but get
no additional comment
Fixes: #148
> amend: respect git config commit.cleanup

- docs/amend.md
Update the doc to reflect the new conflict behavior
and settings for cleanup/comment char.
> amend: Update docs

- setup.cfg
Another undeclared dependency of aiohttp
> setup: Add attrs dependency

- revup/topic_stack.py
Missing a space and a `f` here
Topic: revup-f
> Fix warning formatting

- revup/config.py
- revup/revup.py
This conflicts with argparse's shortening of 1char arguments.
Topic: nn
Reviewers: aaron
> config: Remove -nx negation shortform
