setup.cfg
The asyncio, configparser, and dataclasses modules are distributed as
part of python since at least python 3.7. Since revup requires
python3.8 or above, we can remove these dependencies from the
setup.cfg.
=> setup: Remove core python dependencies

README.md
Don't know why I typed 3.6, that's totally wrong.
=> Fix min git version in README

docs/revup.md, revup/topic_stack.py
Github's review model does not allow the base branch
to live in another fork, making it impossible to use
the relative review model.
Throw an error if using Relative-Branch, and skip topics
that are relative until the base is merged.
Reviewers: greg-b, brian-k
=> Handle Relative across forks

revup/topic_stack.py
Somehow I confused 'continue' for 'pass'.
This was causing the push marking loop logic
to get totally skipped, resulting in crashes
and cases where commit ids could not be found
in depending reviews.
Topic: mistake
Reviewers: brian-k, greg
Fixes: #6
=> Fix mistaken 'continue' in rebase logic

README.md, pyproject.toml, setup.cfg, setup.py
Scrub the README and replace local links with global links
that pypi can access. Remove the extra dark mode tags that pypi
can't recognize.
Topic: setuppy
=> Add setup.py to handle pypizing README

Makefile, setup.cfg, setup.py
Fix man files not being included.
Fix deprecation warnings related to licenses field and
packages.
Fix git revision not being found correctly because setup.py
is executed in a tmp directory. Instead find the revision
in the makefile and pass it into setup.
Topic: fixes
Reviewers: brian-k, aaron
=> Fix warnings and errors with setup

revup/__main__.py, revup/github.py, revup/github_real.py, revup/types.py, revup/upload.py
If there's a github error, print out the indivudual
messages rather than showing the user the raw json.
Also always print out the topics at the end for updates,
since an error at that stage could still mean that most
operations succeeded.
Topic: errors
=> Add better error handling for github responses

docs/revup.md, revup/revup.py
This command is an alias to "revup amend --insert"
Topic: revup_commit
=> Add a command revup commit

docs/amend.md, revup/amend.py
The original ordering was arbitrary, this change
makes it possible to alias "revup commit" as
"revup amend --insert". Previously it would have
been impossible to use --insert to create the top
commit.
Topic: insert
Reviewers: brian-k, malcolm-l
=> amend --insert inserts after given commit

revup/upload.py
When a pre-upload script prints to stdout/stderr, it would print
immediately after the "Running pre-upload command" line (without a
line break or space). If the command failed, the resulting console
error message was empty (resulting in a blank 'E:' line).
Fix both of these by capturing output from the pre-upload script and
stuff it into the exception. When the exception is caught later, the
stdout/stderr will be printed to the console separately with the 'E:'
prefix.
This has the side-effect of suppressing output when the script is
successful.
=> upload: Clean up error messages from pre-upload scripts

revup/topic_stack.py
Rather than print an error we should just print
"Nothing to upload" here.
Topic: exp
=> Remove exceptions for no commits/topics found

revup/amend.py, revup/topic_stack.py
It now caches the status and further calls do nothing.
This allows slightly cleaner flow in amend where the
object is constructed always, but is only populated based
on custom logic where necessary.
Topic: topics_populate
Reviewers: brian-k, malcolm-l
=> Make populate_topics repeatable

revup/git.py
We don't need a binary patch in order to apply
because we just use object ids for 3way.
Git patch-id is broken for all binary diffs, although
its slightly less broken if there is no patch -- it just
produces the same patch-id rather than breaking parsing
for the rest of the commit.
Topic: patchid
=> git: Remove --binary from diff args

revup/git.py, revup/revup.py
Switch to using a windows compatible "which"
function and properly catch the error if "man" is
not found.
Topic: win
Fixes: 66
=> shell: Fixes for windows

revup/git.py
cp doesn't exist on windows either.
Topic: morewindows
=> shell: use shutil.copy rather than cp

revup/topic_stack.py
The "-" specifier for non-zero padded numbers is unix only.
Switch to a new format mechanism that is portable.
Topic: win_date
=> Fix windows date issue

revup/github_utils.py
Github ssh URLS can have any user, not just "git@github.com".
Update the regex to handle this.
Topic: ssh
Closes: 72
=> github: Allow any ssh user in remote url

revup/github_utils.py
Adding full team support looks like a medium task,
but for now we can at least not crash.
Topic: teams
closes #73
=> github: Don't crash if a team is a reviewer

revup/github_utils.py
This requires a new permission for your access token, and
we don't want to make everyone add that.
Topic: teams
=> github: Don't query teams yet

revup/git.py, revup/github_utils.py, revup/revup.py
If we're in a repo with no remote, or no github remote, don't
attempt the topics lookup at all as we assume the user isn't
using "revup upload" in this repo.
This slightly speeds up and avoids some errors.
Topic: amend_lookup
=> amend: Don't attempt to lookup topics if no github remote

revup/topic_stack.py
Previously we just made the first virtual diff target with no parent
resulting in a branch with no shared history with any other
branch. Strictly this shouldn't matter as we only use the
branch for diffs, but we've seen a few cases where pushing this
branch is specifically causing git push to take an incredibly
long time. I don't have a great way to explain this as the virtual
diff target should only be pushing the tree itself, all blobs within
it reuse blobs that were already present in the repo.
Try to create the target with a shared history from an
arbitrary commit to see if this resolves the issues we see.
Topic: vritdiff
=> patchsets: Make virtual diff target with shared history

revup/__main__.py, revup/github_real.py, revup/types.py
Previously we could get responses from the github api like:
```
Response status: 401 took 0.21685314178466797
Response JSON:
{
"message": "Bad credentials",
"documentation_url": "https://docs.github.com/graphql"
}
```
But continue on and fail with something like:
```
Traceback (most recent call last):
File "/.../lib/python3.8/site-packages/revup/__main__.py", line 17, in _main
sys.exit(asyncio.run(main()))
File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/.../lib/python3.8/site-packages/revup/revup.py", line 357, in main
return await upload.main(
File "/.../lib/python3.8/site-packages/revup/upload.py", line 46, in main
await …
```
=> Fail on bad response status

revup/__main__.py
At least some of the time, the response can look like:
```
{'errors': [{'message': 'Parse error on "poopy" (IDENTIFIER) at [1, 1]', 'locations': [{'line': 1, 'column': 1}]}]}
```
which means the handler code throws with something like:
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/.../revup/__main__.py", line 29, in _main
logging.error("{}: {}".format(error["type"], error["message"]))
KeyError: 'type'
```
Now you'll get something like:
```
E: Unknown Error: Parse error on "poopy" (IDENTIFIER) at [1, 1]
W: 1 operations failed!
```
Not sure if some errors still contain `type`, or if the GitHub GraphQL
API doesn't return that anymore.  Either way, handling both cases.
Topic: unknown-error-types
=> Fix error messages for unknown error types

revup/git.py
When making a virtual diff target of an empty old_head,
we would first find the diff of the commit. However if this
diff is empty, we'd pass an empty string to git update-index
which would then hang as it is expecting at least one input.
Solution is to not call update-index at all if there is no diff
as it is not necessary. We can just return new_base.
Topic: fix_hang
=> git: Don't update index if file list is empty

revup/revup.py
This is one older than the latest release, and is required
for new flags as well as the merge-tree command.
Topic: bump
=> Bump required git version to 2.39

revup/git.py
The patches to fix the whitespace issues with revup upload
have made it into mainstream git. We just need to enable the
new whitespace included patch id with the new flag.
This should fix issues where revup upload thinks no changes have
been made even though some have, but only to whitespace.
Topic: ws
=> Pass --verbatim to git patch-id

revup/git.py
The intent of this was to check whether an origin branch
by this name exists, but it was checking local branches.
This fixes some errors for repos that don't have a local
branch called "main" or "master".
Topic: erbr
=> Avoid main branch not found error.

docs/upload.md, revup/revup.py, revup/topic_stack.py, revup/upload.py
As a list of multiple arguments to upload.
If topics are specified, only those topics will be uploaded.
Those topics will also ignore no-self-authored-only.
Any topics that aren't found will warn.
Topic: onlytopics
=> Allow specifying topics to upload

revup/topic_stack.py
This makes the patch id process slightly faster for topics
with multiple commits.
Topic: async
=> Use asyncio.gather to run patch-ids in parallel

docs/upload.md, revup/git.py, revup/revup.py, revup/topic_stack.py, revup/upload.py
Sometimes a user may want to upload a full stack that is
different than their current HEAD (perhaps something just
fetched from remote, but they can save effort by not needing
to check out). This adds a flag so that any ref can be used
as HEAD instead.
Topic: head
=> upload: Allow any head to be specified

docs/config.md, docs/revup.md, revup/config.py, revup/revup.py
In order to simplify the config code and provide people
an easier way to edit their configs, move most of the writing
logic out of the read() fn and into write() and set_value()
functions. Running normal revup commands will no longer write
to the config, instead only "revup config" will be able
to write arbitrary config values. This means that users will
no longer be required to enter an oauth for commands that
don't talk to github, and if a command requires oauth, it
will instead prompt users to run "revup config".
Topic: config
=> config: Reorganize config code and add config command

revup/topic_stack.py
Catch the common case of someone sticking an invalid char in the topic
line.
Topic: catch1-./Q
=> Validate topic names

revup/git.py, revup/topic_stack.py
Previously this logic checked only if topic was on top
of its relative branch. If it had no relative branch, it
always assumed the base is correct, which may not be true.
Update the logic for non-relative reviews to check if the remote
parent commit is an ancestor of the local base ref. If it is,
this indicates that the review should be a rebase. If it is not,
the base must have moved and the review needs to be pushed.
This will take a tiny bit more time to run for cases where the
ancestor check triggers (patch ids match but parent doesn't match
exactly).
Topic: uploadbase
=> upload: Improve is_on_correct_base logic

Makefile
Just a suggestion - this makes the makefile work out-of-the-box in
environments with other python versions besides 3.8
Topic: make-py3
=> Makefile uses python3

revup/topic_stack.py, revup/upload.py
amend will populate topics so that it can use topic names
to locate commits. However in the case that there is format
or usage error in the commit text, we don't want to raise
at this point since it prevents amend from being used to fix
it in the first place.
Topic: raise
=> Only raise in parse_topics when uploading

revup/amend.py, revup/cherry_pick.py, revup/git.py, revup/topic_stack.py
Simple commands such as ref existence, id lookup,
and distance lookup are pretty common and could be
called with the same args at a higher level such that
its difficult to dedupe between calls. To speed things
up, add a lru_cache decorator so that later calls are
looked up. We don't add this to everything since
more complex functions are unlikely to be called with
the same args multiple times.
These calls are mostly pure functions since revup
generally doesn't change the git database. There are
a few exceptions to that, when it runs "reset" for certain
commands. In these cases, we empty all caches just to be safe.
Topic: cache
=> Add a simple LRU cache to common git cmds

revup/__main__.py, revup/amend.py, revup/git.py, revup/logs.py, revup/restack.py, revup/topic_stack.py, revup/types.py, revup/upload.py
Previously we used a git apply backend that did the job,
but doesn't allow for in depth conflict info. git 2.39
introduces a new git merge-tree command that is simpler,
faster, and provides in depth output about various conflict
types, including conflict types that can't be represented
by conflict markers.
Switch to using merge-tree for usages of synthetic cherry-pick
and amend. Virtual diff sets still use the temp index mechanism
for now since merge-tree does not handle that case.
Dump file conflict markers as well as conflict info whenever
possible.
Topic: merge_tree
Relative: cache
=> git: Switch cherry-pick backend to git merge-tree

revup/topic_stack.py
When using a fork this prefix is confusing since the
PR is pushed to origin but the github repo used is "fork".
When not using a fork there is only one remote so it isn't
useful. To simplify both cases, don't print the prefix.
Topic: nopre
Reviewers: brian-k, aaron-m
=> Remove remote prefix from upload printout

revup/git.py, setup.cfg
Turns out functools.lru_cache doesn't actually work for
coroutines, it ends up caching the coroutine itself which
is useless and crashes if called again.
Switch to async_lru, which provides a dropin replacement.
Topic: async_lru
=> Switch to async_lru for lru_cache()

revup/topic_stack.py
When skipping topics because they are not explicitly
specified, make sure to remove them from self.topics
(we also do this for self authored only). Otherwise they
can result in errors down the line as self.topics is used
for other checks.
Also don't delete the topic from the limit_topics list as
that messes up checks in later iterations. Instead check against
self.topics when printing out missing topics later.
Topic: topicsonly
Reviewers: brian-k, aaron
=> Delete topic from list if skipping

revup/git.py
In order to show a better error to the user, catch shell
return codes and raise RevupUsageException.
Topic: catch
Reviewers: brian-k, aaron
=> git: Don't show clean error if failing to translate commit hash

revup/__main__.py, revup/github_utils.py, revup/types.py
Its pretty common for us to hit the 10s github
timeout for very large graphql mutations. In pretty
much all of these cases though, the actual changes
in the request did go through, and a subsequent
revup upload will show everything up to date.
To reflect this and make it nicer for users, catch any
github exception that contains 'timeout' and turn it
into a warning instead. This ensures that we show the topic
list. If the user wishes, they can rerun the command to
verify the changes were actually successful.
Topic: githubtimeout
=> Catch and warn on github timeouts

revup/amend.py
Previous change to amend tried to eliminate a double-call
of write-tree, which was both used to elide the final cherrypick
as well as make the temp commit that is used for cherry-picking.
However it erroneously didn't set the top tree for the len == 1
case which meant that amends of HEAD itself did not actually
do any amending.
Fix this by writing the tree in the correct line, and pointing
the temp commit to that tree. This still manages to avoid a
double call to write-tree. Because drop is always false when
making the temp commit, we know the tree must have been written
earlier.
=> amend: Fix amending HEAD

revup/git.py
It seems like rev-parse --verify if given a valid full length
sha hash doesn't look it up in the database by default, it just
returns success. In order to force it to verify that it is a commit,
we need to add an addl string to the command.
=> git: Add ^commit to rev parse --verify

revup/amend.py, revup/revup.py
Otherwise in order to run with edit false by
default and manually setting it to true, you'd be
passing in --no-no-edit which is silly.
=> amend: Fix double negative in no-edit

setup.cfg
Most of these are actually dependencies of aiohttp
but it seem like they're not declared there, causing some
missing package errors for users.
I think if we declare them here it will fix this
issue.
=> setup: Add missing transitive dependencies

README.md
This changed recently with the git merge-tree use, update
readme accordingly.
Closes: #122
=> readme: Update min git version

docs/amend.md, revup/amend.py
If a user has configured edit=False but specifies --insert,
the intention is clear enough that they do in fact want to edit.
We can automatically assume this without throwing an error and
forcing them to type out --edit
=> amend: Force editing if inserting instead of throwing error

revup/amend.py
The `amend` command breaks when your git editor path (`git editor core.config`) contains spaces. For example, on my windows machine this option is configured to
```
"C:\\Program Files\\Sublime Text 3\\subl.exe" -w
```
Calling `split()` on this string obviously won't end well. This PR uses `shlex.split()` (thanks ChatGPT!) which returns the array 
```
['"C:\\Program Files\\Sublime Text 3\\subl.exe"', '-w']
```
as expected.
=> Add support for git editor paths containing spaces

Makefile
Fixes this error with py 3.10 on test:
mypy: error: ambiguous option: --show-error-code could match --show-error-codes, --show-error-code-links
=> makefile: Fix mypy invocation

revup/__main__.py
Switched from `asyncio.run()` to the older style `asyncio.get_event_loop.run_until_complete()`.
Tested on Ubuntu 22.04 and Windows 10. I also tried raising an exception inside `main()` in revup.py to ensure that errors aren't hidden. The only difference seems to be to avoid the premature closing of the event loop in the ProactorEventLoop (which is the only event loop that works with subprocess on Windows).
See [Asyncio event loop is closed when using asyncio.run()](https://stackoverflow.com/questions/63860576/asyncio-event-loop-is-closed-when-using-asyncio-run) for some discussion.
=> Fix "Event loop is closed" error on windows

revup/shell.py
This used to work but somehow got broken by a mypy
version upgrade. Now the output of gather is treated
as a list and as a result type info by index is not
preserved. We have to manually declare the types by
asserting for it to be happy.
=> shell: Fix broken mypy linting on asyncio.gather()

.github/workflows/makefile.yml
Update minor versions to the latest releases and
test on 3.12 rather than 3.9.
=> github: Update python minor versions

revup/git.py, revup/revup.py
If no `github_oauth` is defined, try to read it from `git credential fill`.
Tested with git-credential-manager.
Note: we don't provide success/fail feedback currently, so expired tokens won't
be invalidated by us.
Fixes: #129
=> Read github credentials from git credential helper

Makefile
Not sure how this broke but I was seeing literal
\n instead of newlines in the generated header +
markdown, which then confuses pandoc and causes man
pages to be formatted wrong.
Switch to using a multiline make variable that is
then exported as a shell variable so newlines are
retained. This also makes it cleaner anyways.
=> makefile: Fix newlines in revup man headers

revup/git.py
Users can install a custom diff frontend for
"git diff" that displays diffs in a different
format, but is not compatible with patch-id. To
make sure this doesn't break revup, run diffs with
--no-ext-diff to ensure that only core diff is used.
=> git: Run diff with --no-ext-diff

Makefile, setup.cfg
Black keeps updating in the background and breaking our
CI due to slightly different formatting between versions.
Fix this by pinning the version.
=> makefile: Pin black version

revup/revup.py, revup/toolkit.py
The list-topics command lists the topics for the current branch along
with (optionally) the commit ID or commit title of all commits that
are part of the topic. This is useful for scripts that needs a list of
the available topics (e.g. in a prepare-commit-msg git hook).
=> toolkit: Add list-topics command

revup/github_real.py
Try to get some more info from this trace
File "/home/jerry/revup/revup/github_real.py", line 78, in graphql
r = await resp.json()
File "/home/jerry/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1165, in json
raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.github.com/graphql')
=> github: Also catch ContentTypeError

revup/github_utils.py
This fixes a longstanding annoying issue where github
queries users based on any match within username, whereas
generally people don't intend to use it this way.
When picking a valid user match, require the prefix to match
the stated query in addition to looking for the minimum size.
=> github: Don't match a user unless the prefix is correct

scripts/analyze_prs.py
Don't error out if num users provided is greater than
returned total.
Drop users with 0 total prs.
Always sort by both total and revup_total, order changing
depending on args. This way listing of users with the
same number in one will still be sorted in the other.
Print percents in a few places as well.
=> Small analyze_prs improvements

revup/amend.py
Similarly we can respect the configured comment character
pretty easily by using it instead of # when applicable.
=> amend: respect core.commentChar

revup/topic_stack.py, revup/upload.py
This sets the function up to allow arbitrary topic
order in the future.
The first pass handles finding the relative topic, but
does not assume it's already populated. The second pass
needs to assume that the relative is already populated
since it uses it, so it needs to be done in topological
order (which is a followup pr).
=> upload: Split populate reviews into 2 phases

docs/upload.md, revup/topic_stack.py
Now that we're iterating over topics topologically
in the important places, we can remove the check
that requires topics to be in consecutive order.
This means revup is able to pull together relative
chains in any arbitrary order, as long as that order
is valid with no cycles.
Fixes: #156
=> upload: Allow arbitrary topic order

docs/restack.md, revup/restack.py, revup/topic_stack.py
Restack will now topologically reorder your relative
graph to be linear again. Update docs to reflect this
and the conflict handling.
=> restack: Be topological and update docs

docs/upload.md, revup/topic_stack.py
This allows you to manually specify one or more prs
as no-update while maintaining the default option for
all other prs. (and vise versa)
Fixes: #140
=> upload: Support Update-Pr-Body as a commit tag

revup/cherry_pick.py
Useful if cherry-picking from a relative topic chain.
It would be nice if we could automatically cherry-pick just the commits
from a particular topic without needing to specify the previous topic as
the base-branch, but that would require either fetching "more stuff"
from the remote and doing some guessing, or querying the github API,
both of which are a bit more complicated
Topic: cherry-pick-relative
=> Cherry-pick can fetch base-branch

docs/upload.md, revup/revup.py, revup/topic_stack.py, revup/upload.py
Branch-format will let you control how branches are named,
which has an effect on when branches collide. This can be
set on cmdline, from config file, or on a topic-by-topic
basis inside the commit text.
user+branch is the default today and will remain the default.
Branch names will never collide if using this, but you cannot
retarget to other base branches, and you must use Uploader: if
another user wants to push to this branch.
user allows retargeting prs to other base branches, but will
not allow multiple base-branches to be specified. if they are,
it will warn to specify user+branch instead.
branch will allow others to upload to the same pr, but uploader:
cannot be used.
none includes both limitations and features of user and branch.
I don't really believe there's good use cases for …
=> upload: Add "branch-format" config option and commit tag

revup/amend.py
Revup's default COMMIT_EDITMSG does not have a trailing newline; as a
result, the regex used for matching comment lines when cleanup_type is
'strip' will not match the last line in the message and can leave a
trailing comment line. Fix this by making the trailing newline
optional in the regex.
Fixes: 24012d1 ("amend: respect git config commit.cleanup")
=> amend: Correctly strip comments with no trailing newline

revup/git.py, revup/revup.py
The slash is incorrect according to https://github.com/Skydio/revup/pull/131#discussion_r1548896688
"The leading "/" here is incorrect btw, and fails for credential helpers
that do naive string matching on URL path 😞. It should be just
path=f"{fork_info.owner}/{fork_info.name}.git""
=> credential: Remove leading slash before path

revup/git.py, revup/logs.py, revup/revup.py, revup/shell.py
This ensures that the token is not printed to stdout
even when using verbose, either with the stdout of the
git operation, or thereafter.
=> git: Properly redact oauth from git credential

revup/topic_stack.py
If there are two PRs in a relative chain where one PR's URL is a
prefix of another (e.g. when PR 24 is relative to PR 2), the review
graph comment will incorrectly modify the second URL by inserting '**'
at the start and in the middle of the URL. This is due to the naive
string replacement checking for any occurance of each URL.
Fix this by searching instead for the URL followed by the review title
and replacing them both at once instead of individually. This is also
slightly more efficient since there are fewer strings allocated.
=> upload: Fix review graph comment

docs/upload.md, revup/revup.py, revup/upload.py
This is similar to to dry-run except it will also push your
branches for you. This can be used to either create PRS manually
in github or with other code review backends that we haven't integrated
yet.
Topic: ponly
Fixes: #179
=> upload: Add a --push-only flag

revup/github_utils.py
Bots apparently don't have a "login" field.
Topic: ghbot
Fixes: #178
=> github: Don't crash if github bot is a reviewer

revup/revup.py
2.40 is specified in the README but we were only enforcing
2.39, which was missing some flags to merge-tree.
Topic: gitv1
=> git: Correctly bump git version to 2.40

README.md, revup/revup.py
This gets us access to the --merge-base and -X flags to
"git merge-tree"
=> git: Bump git supported version to 2.43

revup/amend.py
If the only staged changes are pure renames, 'git diff --cached
--quiet' will not report any changes. As a result, attempting to
'revup amend' would skip writing a new tree for the commit and the
rename would still be staged rather than added to the amended commit.
Fix this by turning off rename detection when checking for staged
changes in 'revup amend'. This should be slightly more efficient as
well.
=> amend: Allow amending with pure renames

README.md
This PR improves the GitHub Personal Access Token setup instructions in the README to enhance accessibility and user experience.
Changes:
- Replace generic "here" link text with more descriptive "GitHub Personal Access Token" for better accessibility
- Add `?scopes=repo` query parameter to pre-select required permissions
- Update permission description from "full repo permissions" to more accurate "repo" scope
=> docs: improve GitHub token setup instructions for better accessibility and clarity

revup/git.py
The '.' character is valid in repository names on github. Change the
regexes to use negative lookbehind assertions to avoid matching an
optional trailing '.git' instead of stopping the repository name when
encountering '.'.
Without this, revup cannot be used on repositories containing the '.'
character.
=> git: Correctly match repository names containing '.'

revup/git.py
This causes git commands to run without considering any
system or user configuration. In some cases it's easier to
ban all overrides rather than have to override things on
a flag by flag basis.
=> git: Add option for no_config in git shell

revup/git.py
Previously patchsets used a hacky invocation of update-index
to overlay changed files from old tree to new tree. In addition
to being slower than necessary, this has the downside of showing
upstream changes in the diff, even those that were not changed
in the given review upload.
Using git merge-tree for this instead is cleaner, faster, and better.
We do this by "cherry-picking" the old branch with git merge-tree, but providing -X ours as
the strategy. This provides a tree that looks like the new base with the old changes applied.
For cases where the old changes don't apply cleanly, the ours strategy prevents conflicts by
taking the version in the old tree. Although this can be a bit confusing when looking at the
file as a whole, it provides a succinct way to view a difference between the …
=> git: Use merge-tree in patchsets

revup/topic_stack.py
When originally adding Uploader, we didn't allow relative between
different uploaders to be safe / prevent risk of mistakes. It seems
like there's a decently large use case for this though, so switch to
allowing it.
Topic: relup
Uploader: who
=> upload: Allow relative between different uploaders

revup/shell.py, revup/topic_stack.py
In certain situations "git push" will need to auth interactively. However
we don't show the user any output from git push because of github's automatic
"create a pr test" that is generally not what we want since revup handles pr
creation. This does make these auth situations confusing though.
Instead of hiding all output, default to showing output except for lines prefixed
with "remote:" which will get hidden.
Topic: outpush3
Closes: #33
=> git: Don't swallow all push output

revup/topic_stack.py
The logic for checking whether a PR was improperly merged was allowing
the target branch name, which could be a relative branch. We don't want
that, we only want changes to merge into the base branch of the entire chain.
This also helps handle some reordering issues.
Topic: reorder3
=> upload: Check PRs merge into base branch rather than base ref

revup/topic_stack.py, revup/upload.py
We've had a long running issue where github may mark prs as merged
or closed when trying to reorder relative series. This is caused
by push + update not being atomic (see comments for more details).
To work around this we'll
- detect it in a dumb way, if 2 or more prs had their base changed
this upload. this will result in some false positives, but the only
cost is an additional ~1s push that people likely won't notice, and
will save us from needing to write more complex logic to detect it
correctly.
- push a dummy commit to every single branch initially that prevents
github from marking any of the prs as merged.
- update as normal
- do an extra push to remove the dummy commit
Topic: reorder4
Fixes: #170
=> upload: Push a dummy commit to work around reordering issues

revup/github_utils.py, revup/topic_stack.py
The headRefOid field of a PR actually contains the oid of
whatever the tot of that branch name is, which may not be the
commit that is actually associated with the pr if it has been merged.
To get that correct, we have to query the actual commit list.
This handles a corner case in reordering PRs with the repo's merge
setting as rebase. Somehow this causes one of the reordered PRs to
get merged with 0 commmits, which later causes us to not re-make prs.
With this change, we'll always succeed in remaking prs if they are
erroneously closed or merged on a reorder. Avoiding having them get
closed is a follow-up change.
Topic: query1
=> upload: Query head oid of a PR via commits

revup/revup.py
Add support for GITHUB_TOKEN environment variable in authentication
chain, providing compatibility with GitHub CLI and other GitHub tools.
Environment variable is checked after config file but before git
credential helper fallback.
Priority order:
1. Command line argument (--github-oauth)
2. Config file (~/.revupconfig)
3. Environment variable (GITHUB_TOKEN) [NEW]
4. Git credential helper
5. Error if none found
Features:
- Maintains all existing functionality and fallbacks
- Proper token redaction in logs for security
- Clear debug messaging showing which method was used
- Updated error message to mention environment variable option
This change improves user experience by allowing the same environment
variable used by gh and other GitHub tools, reducing setup friction.
Branch: main
Topic: …
=> Add support for GITHUB_TOKEN environment variable
